#%RAML 1.0 NamedExample
value:
  zone1:
    index: 1
    travelers: []
  zone2:
    index: 2
    travelers: []
  zone3:
    index: 3
    travelers: []
  zone4:
    index: 4
    travelers: []
  zone5:
    index: 5
    travelers: []
  zone6:
    index: 6
    travelers: []
  zone7:
    index: 7
    travelers: []
  onWaitingList:
    index: 8
    travelers: []
  withSSR:
    index: 9
    travelers: []
  withUnassignedSeats:
    index: 10
    travelers:
    - '151568074'
    - '151568077'
    - '151568070'
    - '151568075'