#%RAML 1.0 NamedExample
value:
  warnings:
  - 
    code: '024'
    message: Field PASSENGER CHECKIN CHANNEL COUNT is empty
  errors:
  - 
    code: PRD_001
    message: A null scheduledArriveDateTime was encountered