#%RAML 1.0 NamedExample
value:
  -  
    id: 151568070
    flight:
      type:
      flightId: 1172181
      date: '2021-08-28'
      flightNumber: '413'
      leg: '1'
      flightStatus: OT
      flightType: RF
      divertCode:
      cancelReason:
      readyForBoarding: true
      comments:
      seats:
        total: 177
        open: 165
        booked: 12
        checked: 0
        waitlist: 0
        capacity: 186
      scheduled:
        aircraftType: 32B
        tail:
        make: Airbus
        market: AVLDEN
        origin: AVL
        destination: DEN
        departureLocal: '2021-08-28T08:00:00.000'
        departureGMT: '2021-08-28T12:00:00.000'
        offLocal:
        offGMT:
        arrivalLocal: '2021-08-28T09:14:00.000'
        arrivalGMT: '2021-08-28T15:14:00.000'
      estimated:
        aircraftType:
        tail:
        make:
        market:
        origin:
        destination:
        departureLocal:
        departureGMT:
        offLocal:
        offGMT:
        arrivalLocal:
        arrivalGMT:
      actual:
        aircraftType: 32B
        tail: 253NV
        make: Airbus
        market: AVLDEN
        origin: AVL
        destination: DEN
        departureLocal:
        departureGMT:
        offLocal:
        offGMT:
        arrivalLocal: '2021-08-28T08:51:00.000'
        arrivalGMT: '2021-08-28T14:51:00.000'
      id:
      category: SF
      departureStatus:
        status: ON_TIME
        locationCode: AVL
        terminal:
        gate:
        baggageClaim:
        domestic: true
      arrivalStatus:
        status: ARRIVED
        locationCode: DEN
        terminal:
        gate:
        baggageClaim:
        domestic: true
      delays: []
      passengers:
      bags:
      dispositionReasons: []
    paxNum: '1'
    segment: 1A
    firstName: ALICIA
    lastName: WILSON
    middleName:
    dob: '1971-01-01'
    gender: F
    knownTraveler: TT129H979
    redressNbr:
    confirmationNum: 9VR6TQ
    confirmationId: 56783992
    volunteer: false
    bookType: WB
    employeeHireDate:
    carryOnBagCount: 0
    checkedBagCount: 1
    typeIndicator:
    standByPassenger: false
    standByPriority:
    acknowledgmentRequired: false
    docsVerified: false
    seats:
    bags:
    - id:
      type: PP
      number: 1
      fee: 35
      weight: 0
      overweightLevel: 0
      heavy: false
      oversized: false
      printed: false
      equipmentType:
    boardingPass:
      qrCodeBase64:
      bar2DCodeBase64:
    authorization:
      status: false
      statusCode:
      createdAt: '2021-12-28T06:03:52.627+0000'
      dhsTransmitted: false
      bpSsss: false
      travelDoc: false
      sendToDhsEnabled: false
      knownTraveler: false
    checkIn:
      status: false
      withinWindow: false
      method:
      groupZone: UNASSIGNED
      groupIndex: 10
      createdAt:
      eligibility:
      - channel: 1
        status: false
        journeyStatusCode: FALSE_AFTER_CHECKIN_WINDOW
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 4
        status: false
        journeyStatusCode: FALSE_AFTER_CHECKIN_WINDOW
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 19
        status: false
        journeyStatusCode: FALSE_AFTER_CHECKIN_WINDOW
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 23
        status: false
        journeyStatusCode: FALSE_AFTER_CHECKIN_WINDOW
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 3
        status: false
        journeyStatusCode: FALSE_ONLINE_CHECKIN_TURNED_OFF
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      searchable: true
    board:
      status: false
      createdAt: '2021-12-28T06:03:52.496+0000'
      eligibility: false
      boardingZone: UNASSIGNED
    contacts:
      - id: 14203102
        type: E
        value: test@mail.com
      - id: 14203103
        type: M
        value: '6052805366'
    ssrs:
    asrlStatus:
      active: false
      originalSeat:
      newSeat:
    emergencyContact:
    bagtags: []
    travelerIdentifications: []
    addressWhileInUS:
    finalDestination: DEN
    securityCheckVerifiedId:
  -
    id: 151568077
    flight:
      type:
      flightId: 1172202
      date: '2021-09-01'
      flightNumber: '414'
      leg: '1'
      flightStatus: OT
      flightType: RF
      divertCode:
      cancelReason:
      readyForBoarding: false
      comments:
      seats:
        total: 177
        open: 158
        booked: 19
        checked: 0
        waitlist: 0
        capacity: 186
      scheduled:
        aircraftType: 32B
        tail:
        make: Airbus
        market: AVLDEN
        origin: DEN
        destination: AVL
        departureLocal: '2021-09-01T15:22:00.000'
        departureGMT: '2021-09-01T21:22:00.000'
        offLocal:
        offGMT:
        arrivalLocal: '2021-09-01T20:12:00.000'
        arrivalGMT: '2021-09-02T00:12:00.000'
      estimated:
        aircraftType:
        tail:
        make:
        market:
        origin:
        destination:
        departureLocal:
        departureGMT:
        offLocal:
        offGMT:
        arrivalLocal:
        arrivalGMT:
      actual:
        aircraftType: 32B
        tail: 253NV
        make: Airbus
        market: AVLDEN
        origin: DEN
        destination: AVL
        departureLocal: '2021-09-01T15:19:00.000'
        departureGMT: '2021-09-01T21:19:00.000'
        offLocal: '2021-09-01T15:30:00.000'
        offGMT: '2021-09-01T21:30:00.000'
        arrivalLocal: '2021-09-01T20:01:00.000'
        arrivalGMT: '2021-09-02T00:01:00.000'
      id:
      category: SF
      departureStatus:
        status: DEPARTED
        locationCode: DEN
        terminal:
        gate:
        baggageClaim:
        domestic: true
      arrivalStatus:
        status: ARRIVED
        locationCode: AVL
        terminal:
        gate:
        baggageClaim:
        domestic: true
      delays: []
      passengers:
      bags:
      dispositionReasons: []
    paxNum: '2'
    segment: 2A
    firstName: DARRYL
    lastName: REED
    middleName:
    dob: '1971-01-01'
    gender: M
    knownTraveler:
    redressNbr:
    confirmationNum: 9VR6TQ
    confirmationId: 56783992
    volunteer: false
    bookType: WB
    employeeHireDate:
    carryOnBagCount: 0
    checkedBagCount: 0
    typeIndicator:
    standByPassenger: false
    standByPriority:
    acknowledgmentRequired: false
    docsVerified: false
    seats:
    bags: []
    boardingPass:
      qrCodeBase64:
      bar2DCodeBase64:
    authorization:
      status: false
      statusCode:
      createdAt: '2021-12-28T06:03:52.628+0000'
      dhsTransmitted: false
      bpSsss: false
      travelDoc: false
      sendToDhsEnabled: false
      knownTraveler: false
    checkIn:
      status: false
      withinWindow: false
      method:
      groupZone: UNASSIGNED
      groupIndex: 10
      createdAt:
      eligibility:
      - channel: 1
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 4
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 19
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 23
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 3
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      searchable: false
    board:
      status: false
      createdAt: '2021-12-28T06:03:52.496+0000'
      eligibility: false
      boardingZone: UNASSIGNED
    contacts: []
    ssrs:
    asrlStatus:
      active: false
      originalSeat:
      newSeat:
    emergencyContact:
    bagtags: []
    travelerIdentifications: []
    addressWhileInUS:
    finalDestination: AVL
    securityCheckVerifiedId:
  -
    id: 151568075
    flight:
      type:
      flightId: 1172202
      date: '2021-09-01'
      flightNumber: '414'
      leg: '1'
      flightStatus: OT
      flightType: RF
      divertCode:
      cancelReason:
      readyForBoarding: false
      comments:
      seats:
        total: 177
        open: 158
        booked: 19
        checked: 0
        waitlist: 0
        capacity: 186
      scheduled:
        aircraftType: 32B
        tail:
        make: Airbus
        market: AVLDEN
        origin: DEN
        destination: AVL
        departureLocal: '2021-09-01T15:22:00.000'
        departureGMT: '2021-09-01T21:22:00.000'
        offLocal:
        offGMT:
        arrivalLocal: '2021-09-01T20:12:00.000'
        arrivalGMT: '2021-09-02T00:12:00.000'
      estimated:
        aircraftType:
        tail:
        make:
        market:
        origin:
        destination:
        departureLocal:
        departureGMT:
        offLocal:
        offGMT:
        arrivalLocal:
        arrivalGMT:
      actual:
        aircraftType: 32B
        tail: 253NV
        make: Airbus
        market: AVLDEN
        origin: DEN
        destination: AVL
        departureLocal: '2021-09-01T15:19:00.000'
        departureGMT: '2021-09-01T21:19:00.000'
        offLocal: '2021-09-01T15:30:00.000'
        offGMT: '2021-09-01T21:30:00.000'
        arrivalLocal: '2021-09-01T20:01:00.000'
        arrivalGMT: '2021-09-02T00:01:00.000'
      id:
      category: SF
      departureStatus:
        status: DEPARTED
        locationCode: DEN
        terminal:
        gate:
        baggageClaim:
        domestic: true
      arrivalStatus:
        status: ARRIVED
        locationCode: AVL
        terminal:
        gate:
        baggageClaim:
        domestic: true
      delays: []
      passengers:
      bags:
      dispositionReasons: []
    paxNum: '1'
    segment: 2A
    firstName: ALICIA
    lastName: WILSON
    middleName:
    dob: '1971-01-01'
    gender: F
    knownTraveler: TT129H979
    redressNbr:
    confirmationNum: 9VR6TQ
    confirmationId: 56783992
    volunteer: false
    bookType: WB
    employeeHireDate:
    carryOnBagCount: 0
    checkedBagCount: 1
    typeIndicator:
    standByPassenger: false
    standByPriority:
    acknowledgmentRequired: false
    docsVerified: false
    seats:
    bags:
    - id:
      type: PP
      number: 1
      fee: 35
      weight: 0
      overweightLevel: 0
      heavy: false
      oversized: false
      printed: false
      equipmentType:
    boardingPass:
      qrCodeBase64:
      bar2DCodeBase64:
    authorization:
      status: false
      statusCode:
      createdAt: '2021-12-28T06:03:52.627+0000'
      dhsTransmitted: false
      bpSsss: false
      travelDoc: false
      sendToDhsEnabled: false
      knownTraveler: false
    checkIn:
      status: false
      withinWindow: false
      method:
      groupZone: UNASSIGNED
      groupIndex: 10
      createdAt:
      eligibility:
      - channel: 1
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 4
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 19
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 23
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      - channel: 3
        status: false
        journeyStatusCode: FALSE_FLIGHT_DEPARTED
        travelerStatusCode: FALSE_JOURNEY_CHECKIN_NOT_AVAILABLE
      searchable: false
    board:
      status: false
      createdAt: '2021-12-28T06:03:52.496+0000'
      eligibility: false
      boardingZone: UNASSIGNED
    contacts: []
    ssrs:
    asrlStatus:
      active: false
      originalSeat:
      newSeat:
    emergencyContact:
    bagtags: []
    travelerIdentifications: []
    addressWhileInUS:
    finalDestination: AVL
    securityCheckVerifiedId:
